#!/usr/bin/env bash

echo "prepare..."
rm -rf dist
mkdir -p dist

bin=../../../node_modules/.bin
echo "build src/auth.ls -> dist/index.js ..."
$bin/lsc -cp src/auth.ls > dist/index.js
echo "minify dist/index.js -> dist/index.min.js ..."
$bin/uglifyjs dist/index.js > dist/index.min.js

echo "build authpanel.pug -> dist/index.html ..."
$bin/srcbuild-pug src/authpanel.pug > dist/index.html
echo "build base.pug -> dist/base.html ..."
$bin/srcbuild-pug src/base.pug > dist/base.html

echo "prepare img files"
cp -R src/img/ dist/img/

echo "build server files ..."
$bin/lsc -co dist/lib lib
