#!/usr/bin/env bash

echo "prepare..."
rm -rf dist
mkdir -p dist

echo "build src/index.ls -> dist/index.js ..."
./node_modules/.bin/lsc -cp src/index.ls > dist/index.js
echo "minify dist/index.js -> dist/index.min.js ..."
./node_modules/.bin/uglifyjs dist/index.js > dist/index.min.js

echo "build index.pug -> dist/index.html ..."
./node_modules/.bin/srcbuild-pug src/index.pug > dist/index.html

echo "build server files ..."
node_modules/.bin/lsc -co dist/lib lib
