#!/usr/bin/env bash

echo "prepare..."
rm -rf dist
mkdir -p dist

bin=../../../node_modules/.bin
echo "build captcha.ls -> index.js ..."
$bin/lsc -cp src/captcha.ls > dist/index.js
echo "minify index.js -> index.min.js ..."
$bin/uglifyjs dist/index.js > dist/index.min.js

echo "build index.pug ..."
$bin/srcbuild-pug src/index.pug > dist/index.html

echo "build server files ..."
$bin/lsc -co dist/lib lib
