#!/usr/bin/env bash

echo "prepare..."
rm -rf dist
mkdir -p dist

bin=../../../node_modules/.bin
echo "building consent.ls -> index.js ..."
$bin/lsc -cp --no-header src/consent.ls > dist/index.js
echo "minify index.js -> index.min.js ..."
$bin/uglifyjs dist/index.js -m -c > dist/index.min.js

echo "build consent base ..."
mkdir -p dist/block/base/0.0.1
$bin/srcbuild-pug src/block/base/0.0.1/index.pug > dist/block/base/0.0.1/index.html

echo "build cookie consent  ..."
mkdir -p dist/block/cookie/0.0.1
$bin/srcbuild-pug src/block/cookie/0.0.1/index.pug > dist/block/cookie/0.0.1/index.html

echo "build tos consent  ..."
mkdir -p dist/block/tos/0.0.1
$bin/srcbuild-pug src/block/tos/0.0.1/index.pug > dist/block/tos/0.0.1/index.html

echo "build server files ..."
$bin/lsc -co dist/lib lib
