from: '"#{sitename} Support" <contact@#{domain}>'
subject: 'Email Verification from #{sitename}'
content: |
  You receive this mail because there is an email verification request for the account using this email in #{sitename}. If you didn't sign up #{sitename}, please just ignore this mail, or reply directly to ask removing email.

  To verify your email, click following link:

  [https://#{domain}/auth/mail/verify/#{token}](https://#{domain}/auth/mail/verify/#{token})

  Thanks,
  #{sitename} team
