// Generated by LiveScript 1.6.0
(function(){
  var fs, path;
  fs = require('fs');
  path = require('path');
  (function(it){
    return module.exports = it;
  })(function(backend){
    return function(it){
      return it.apply(backend);
    }(function(){
      return fs.readdirSync(__dirname).filter(function(it){
        return !/^index\./.exec(it);
      }).filter(function(it){
        return !/^\./.exec(it);
      }).map(function(it){
        return path.join(__dirname, it);
      }).filter(function(it){
        return /\.(ls|js)$/.exec(it) || fs.statSync(it).isDirectory();
      }).map(function(it){
        return require(it)(backend);
      });
    });
  });
}).call(this);
