// Generated by LiveScript 1.6.0
(function(){
  var discuss;
  discuss = require('@servebase/discuss');
  (function(it){
    return module.exports = it;
  })(function(backend){
    return discuss(backend);
  });
}).call(this);
