// Generated by LiveScript 1.6.0
(function(){
  var fs, path, lderror, throttle, aux, discuss;
  fs = require('fs');
  path = require('path');
  lderror = require('lderror');
  throttle = require('@servebase/backend/throttle');
  aux = require('@servebase/backend/aux');
  discuss = require('@servebase/discuss');
  (function(it){
    return module.exports = it;
  })(function(backend, arg$){
    var api, app, db, config;
    api = arg$.api, app = arg$.app;
    db = backend.db, config = backend.config;
    return discuss(backend);
  });
}).call(this);
