// Generated by LiveScript 1.6.0
(function(){
  var block, jsdom, dom, ref$, win, doc, mgr;
  block = require('@plotdb/block');
  jsdom = require('jsdom');
  dom = new jsdom.JSDOM("<DOCTYPE html><html><body></body></html>");
  ref$ = [dom.window, dom.window.document], win = ref$[0], doc = ref$[1];
  block.env(win);
  mgr = function(arg$){
    var base;
    base = arg$.base;
    return new block.manager({
      registry: function(d){
        var path;
        if (/^https?:/.exec(d.url)) {
          return d.url;
        } else if (d.url) {
          return base + "/static" + d.url;
        }
        path = d.path || (d.type === 'block'
          ? 'index.html'
          : d.type === 'js' ? 'index.min.js' : 'index.min.css');
        return base + ("/static/assets/lib/" + d.name + "/" + (d.version || 'main') + "/" + path);
      }
    });
  };
  module.exports = mgr;
}).call(this);
