// Generated by LiveScript 1.6.0
(function(){
  var lderror, throttle, aux;
  lderror = require('lderror');
  throttle = require('@servebase/backend/throttle');
  aux = require('@servebase/backend/aux');
  (function(it){
    return module.exports = it;
  })(function(backend, arg$){
    var api, app, db;
    api = arg$.api, app = arg$.app;
    db = backend.db;
    app.get('/', throttle.kit.generic, function(req, res, next){
      return db.query("select count(key) as count from users").then(function(r){
        var count;
        r == null && (r = {});
        count = ((r.rows || (r.rows = []))[0] || {
          count: 0
        }).count;
        return res.render('index.pug', {
          count: count
        });
      });
    });
    app.get('/auth-required', function(req, res, next){
      return lderror.reject(1000);
    });
    app.get('/i18n', function(req, res, next){
      return res.send({
        locale: req.get("I18n-Locale")
      });
    });
    api.get('/error', function(req, res, next){
      throw new Error();
    });
    app.get('/error', function(req, res, next){
      throw new Error();
    });
    api.get('/error/next', function(req, res, next){
      return next(new Error());
    });
    app.get('/error/next', function(req, res, next){
      return next(new Error());
    });
    api.get('/lderror', function(req, res, next){
      return next(lderror(1023));
    });
    app.get('/lderror', function(req, res, next){
      return next(lderror(1023));
    });
    app.get('/error/reject', function(req, res, next){
      return Promise.reject(new Error());
    });
    app.get('/lderror/reject', function(req, res, next){
      return Promise.reject(lderror(1023));
    });
    api.get('/ip', function(req, res, next){
      return res.send(aux.ip(req));
    });
    api.get('/password-due', function(req, res, next){
      return db.userStore.passwordDue({
        user: req.user
      }).then(function(delta){
        return res.send(delta > 0
          ? {
            passwordExpire: delta
          }
          : {});
      });
    });
    api.post('/post', backend.middleware.captcha, function(req, res, next){
      return res.send('pass');
    });
    api.post('/post-test/', function(req, res, next){
      return res.send('pass');
    });
    app.get('/me/settings', aux.signedin, function(req, res, next){
      return res.render('me/settings.pug', {
        user: req.user
      });
    });
    return app.get('/view', function(req, res, next){
      return res.render('view.pug', {
        view: true
      });
    });
  });
}).call(this);
